version: '3.4'

services:
  crmservice:
    image: ${DOCKER_REGISTRY-}crmservice
    build:
      context: .\src\CRMService
      dockerfile: Dockerfile
ports:
      - "44300:80"
    depends_on:
      - db-server
    networks:
      - localdev
       db-server:
    image: microsoft/mssql-server-windows-express
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password123
      - MSSQL_TCP_PORT=1433

    ports:
      - "1400:1433"
    networks:
      - localdev