version: '3.4'

services:
  crmservice:
    build:
      context: .\src\CRMService
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
          SA_PASSWORD: "1q2w3e4r5T"
          ACCEPT_EULA: "Y"